import type { Metadata } from "next";
import "./globals.css";
import "bootstrap/dist/css/bootstrap.min.css";
import Navbar from "@/components/navbar";
export const metadata: Metadata = {
  title: "shiba_inu",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-bs-theme="">
      <body className="bg-scroll">
        <Navbar />
        {children}
      </body>
    </html>
  );
}
